name: dirt_coin
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.3.1
  firebase_messaging: ^15.1.3
  cloud_firestore: ^5.4.4
  intl: ^0.19.0
  dropdown_search: ^5.0.6
  cached_network_image: ^3.3.1
  # shared_preferences: ^2.3.0 # Uncomment for local persistence
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true