// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFb7Fx4nctLkSWhHa9dvrYFc7oded2PP8',
    appId: '1:1080666149157:web:031b6da9a953b8245c8acc',
    messagingSenderId: '1080666149157',
    projectId: 'dirt-coin-b252d',
    authDomain: 'dirt-coin-b252d.firebaseapp.com',
    storageBucket: 'dirt-coin-b252d.firebasestorage.app',
    measurementId: 'G-92GZQRTB8B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz8a-k8DBbXQ3yor_Aqmzaqw4aOPp9v08',
    appId: '1:1080666149157:android:a99b47bd4015c4cd5c8acc',
    messagingSenderId: '1080666149157',
    projectId: 'dirt-coin-b252d',
    storageBucket: 'dirt-coin-b252d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW7hvCibTNq90B-Wu7CGERle7SMjjXVl0',
    appId: '1:1080666149157:ios:c3b4c1b2c7cbb1805c8acc',
    messagingSenderId: '1080666149157',
    projectId: 'dirt-coin-b252d',
    storageBucket: 'dirt-coin-b252d.firebasestorage.app',
    iosBundleId: 'com.example.dirtCoin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW7hvCibTNq90B-Wu7CGERle7SMjjXVl0',
    appId: '1:1080666149157:ios:c3b4c1b2c7cbb1805c8acc',
    messagingSenderId: '1080666149157',
    projectId: 'dirt-coin-b252d',
    storageBucket: 'dirt-coin-b252d.firebasestorage.app',
    iosBundleId: 'com.example.dirtCoin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFb7Fx4nctLkSWhHa9dvrYFc7oded2PP8',
    appId: '1:1080666149157:web:c8844cfa1289db8a5c8acc',
    messagingSenderId: '1080666149157',
    projectId: 'dirt-coin-b252d',
    authDomain: 'dirt-coin-b252d.firebaseapp.com',
    storageBucket: 'dirt-coin-b252d.firebasestorage.app',
    measurementId: 'G-4KVJYP876T',
  );
}
